/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as ExercisesIdRouteImport } from './routes/exercises.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExercisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/workout': typeof WorkoutRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises/': typeof ExercisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/profile': typeof ProfileRoute
  '/workout': typeof WorkoutRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises': typeof ExercisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/workout': typeof WorkoutRoute
  '/exercises/$id': typeof ExercisesIdRoute
  '/exercises/': typeof ExercisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/exercises'
    | '/profile'
    | '/workout'
    | '/exercises/$id'
    | '/exercises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/profile'
    | '/workout'
    | '/exercises/$id'
    | '/exercises'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/exercises'
    | '/profile'
    | '/workout'
    | '/exercises/$id'
    | '/exercises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
  }
}

interface ExercisesRouteChildren {
  ExercisesIdRoute: typeof ExercisesIdRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesIdRoute: ExercisesIdRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
